import './globals.css';

import "primereact/resources/themes/viva-dark/theme.css";     
import "primereact/resources/primereact.min.css";   
import "primeicons/primeicons.css"

import { Nav } from '@/components';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='min-h-screen'>
        <Nav />
        <div className='bg-[#0e1315]'>
          {children}
        </div>
      </body>
    </html>
  )
}
